export const projects = [
    {
        id: 1,
        slug: "perfect-baby-fit",
        title: "Perfect Baby Fit",
        about: "React project for choosing the perfect size of clothes for a child. Develop complicated filters with different params, multilingual, pagination",
        link: "#",
        technologies: "React, React Router, Redux, Redux Saga, Redux Toolkit, yup, i18n, SCSS, REST API, Swagger, Figma",
        image: "/../public/baby-fit.jpg",
        imageMobile: "/../public/baby-fit-mobile.jpg",
    },
    {
        id: 2,
        slug: "onlime-store",
        title: "Onlime store",
        about: "Online store of digital equipment and gadgets. Develop products compare table, basket, theme change",
        link: "#",
        technologies: "Laravel blades, jQuery, SCSS, Alpine.js, AJAX.",
        image: "/../public/onlime-store.jpg",
        imageMobile: "/../public/onlime-mobile.jpg",
    },
    {
        id: 3,
        slug: "svitanok",
        title: "Svitanok juice",
        about: "Landing for juice company with cute animation.",
        link: "http://www.svitanok-juice.com.ua/",
        technologies: "Laravel blades, jQuery, SCSS.",
        image: "/../public/svitanok.jpg",
        imageMobile: "/../public/svitanok-mobile.jpg",
    },
    {
        id: 4,
        slug: "code-of-the-nation",
        title: "Code of the nation",
        about: "Website for the charitable fund Code of the nation.",
        link: "https://code-of-nation.org.ua/",
        technologies: "Laravel blades, jQuery, SCSS, AJAX, Leaflet.js.",
        image: "/../public/kod-of-nation.jpg",
        imageMobile: "/../public/code-mobile.jpg",
    },
    {
        id: 5,
        slug: "harvest-victory",
        title: "Harvest victory",
        about: "Website for the charitable fund Victory harvest. ",
        link: "https://victoryharvest.com.ua/",
        technologies: "Laravel blades, jQuery, SCSS, AJAX.",
        image: "/../public/harvest.jpg",
        imageMobile: "/../public/harvest-mobile.jpg",
    },
    {
        id: 6,
        slug: "download-center",
        title: "Download Center",
        about: "Download Center for IEC Telecom company.",
        link: "https://downloadcenter.iec-telecom.com/",
        technologies: "Laravel blades, jQuery, SCSS, AJAX.",
        image: "/../public/download-center.jpg",
        imageMobile: "/../public/download-mobile.jpg",
    },
    {
        id: 7,
        slug: "irina",
        title: "IRINA NIZHNIK",
        about: "IRINA NIZHNIK.",
        link: "#",
        technologies: "Laravel blades, jQuery, SCSS, AJAX, Aos.",
        image: "/../public/irina.jpg",
        imageMobile: "/../public/irina-mobile.jpg",
    },
]