import './globals.scss'
import {Inter} from 'next/font/google'
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import '../styles/_variables.scss';
import {ThemeProvider} from "../context/ThemeContext";
import {SessionProvider} from "next-auth/react";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body className={inter.className}>
            <ThemeProvider >
                <SessionProvider>
                    <div className="container">
                        <Navbar/>
                        {children}
                        <Footer/>
                    </div>
                </SessionProvider>
            </ThemeProvider>
            </body>
        </html>
    )
}
